---
- name: Install nginx
  apt:
    pkg:
    - nginx
    - nodejs
    - npm
    state: present
    update_cache: yes

- name: Init nginx
  service:
    name: nginx
    state: started

- name: create dir /app
  file:
    path: /app
    state: directory

- name: copy my app to /app
  copy:
    src: my-app
    dest: /app/my-app

- name: copy app.service
  copy:
    src: app.service
    dest: /etc/systemd/system/app.service

- name: enable app
  systemd:
    name: app
    enabled: yes

- name: run app service
  systemd:
    name: app
    state: started

- name: copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: reload nginx

