- hosts: all
  become: yes
  roles:
    # - install_nginx
    - install_docker

- hosts: manager
  become: yes
  roles:
    - docker_swarm_manager

- hosts: worker
  become: yes
  roles:
    - docker_swarm_worker

- hosts: manager
  become: yes
  roles:
    - deploy_stack
