spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  kafka:
    bootstrap-servers: localhost:9092