spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.generate_statistics]": true
      "[hibernate.connection.provider_disables_autocommit]": true
  kafka:
    bootstrap-servers: kafka:29092
  flyway:
    clean-disabled: false