apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec: 
  replicas: 10
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80